SUPER_ADMIN=ALL|admin123


SUPER_USER=CREATE_ACCOUNT,VIEW_ACCOUNTS,EDIT_USER,DELETE_USER|user123

USER=DEPOSIT,WITHDRAW,TRANSFER,HISTORY,BALANCE|userpass
YASMEEN_TAMBOLI=CREATE_ACCOUNT,VIEW_ACCOUNTS,EDIT_USER,DELETE_USER|yasmeen123
KAJAL_SHUKLA=CREATE_ACCOUNT,VIEW_ACCOUNTS,EDIT_USER,DELETE_USER|Kajal123