SUPER_ADMIN=ALL|admin123
SUPER_USER=CREATE_ACCOUNT,VIEW_ACCOUNTS|user123
CHARAN_SINGH=CREATE_ACCOUNT,VIEW_ACCOUNTS|charan
KARTIKEY SINGH=CREATE_ACCOUNT,VIEW_ACCOUNTS|kartikey123
ANUP_SHUKLA=CREATE_ACCOUNT,VIEW_ACCOUNTS|anup123